export { scripts } from './tasks/scripts';
export { globalStyles, blockStyles, tailwindStyles, setupStyles, adminStyles } from './tasks/styles';
export { fonts } from './tasks/fonts';
export { templates } from './tasks/templates';
export { phpcs, phpcbf } from './tasks/php';
export { images } from './tasks/images';
export { svgs } from './tasks/svgs';
export { sprite } from './tasks/sprite';
export { clean } from './tasks/clean';
export { monitor } from './tasks/monitor';
export { vendors } from './tasks/vendors';
